version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    volumes:
      - db-data:/var/lib/mysql:cached

  back:
    build:
      context: ./backend
      args:
        WORKDIR: $WORKDIR
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./backend:/$WORKDIR
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - "$BACKEND_PORT:$CONTAINER_PORT"

  front:
    build:
      context: ./frontend
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
    command: yarn run dev
    volumes:
      - ./frontend:/$WORKDIR
    ports:
      - "$FRONTEND_PORT:$CONTAINER_PORT"
    depends_on:
      - back
    tty: true
    stdin_open: true

volumes:
  db-data:
